### ISSUE TITLE
Tag field querying

### ISSUE THREAD

**Issue by lizdeika** [npezza93/redi_search#16]
**Is your feature request related to a problem? Please describe.**
Currently tag field querying is done like this:
```sql
FT.SEARCH sales_orders_development "`SMTH`|(@tag_field_1:`SMTH`)|(@field_2:`SMTH`) (@field3:(`value`))" NOCONTENT SORTBY id desc
```

Tag field quering needs a special syntax: https://oss.redislabs.com/redisearch/Tags.html#querying_tag_fields

**Describe the solution you'd like**
```sql
FT.SEARCH sales_orders_development "`SMTH`|(@tag_field_1:{`SMTH`})|(@field_2:`SMTH`) (@field3:(`value`))" NOCONTENT SORTBY id desc
```

**Describe alternatives you've considered**
For now I use a workaround like this:
```ruby
index.search.where(tag_field_1: "{SMTH}")
```
It works
But it's kinda hacky and resulting query is like this:
```sql
FT.SEARCH sales_orders_development "`SMTH`|(@tag_field_1:`{SMTH}`)|(@field_2:`SMTH`) (@field3:(`value`))" NOCONTENT SORTBY id desc
```

Thank you

**Comment by npezza93** [comment]
Added in https://github.com/npezza93/redi_search/commit/0d6cde770aa7b9065bd0a785bdb391d5bf6bea79
