### ISSUE TITLE
Add support for Rails 7: Correct dependency

### ISSUE THREAD

**Issue by john-999** [npezza93/redi_search#26]
**Describe the bug**
Rails 7 was launched in 2021, but `redi_search 1.0.5` still depends on `activemodel (< 6.1, >= 5.1)`

**To Reproduce**
1. Add gem `"redi_search", "~> 1.0"` to Gemfile
2. `$ bundle install`

**Comment by npezza93** [comment]
Version 1 was released in 2019. Version 6 is the latest version and is compatible.
