### ISSUE TITLE
Model.where doesn't guarantee order

### ISSUE THREAD

**Issue by decaffeinatedio** [npezza93/redi_search#29]
**Describe the bug**
I believe the `.results` method could be improved: 

```
    def results
      if model
        no_content unless loaded?

        model.where(id: to_a.map(&:document_id_without_index))
      else
        to_a
      end
    end
```

model.where(id: []) doesn't guarantee the order of the IDs, so the best results from Redis aren't necessarily at the top of the model results. 

**To Reproduce**

**Expected behavior**
The results match the order returned by Redis -- most relevant at the top. 

I resolved this using some gross Arel.sql, but maybe there is a better way?
`MyModel.where(id: result_ids).order(Arel.sql("position(id::text in '#{result_ids.join(',')}')"))`

**Screenshots**

**Comment by npezza93** [comment]
We can use in_order_of https://www.bigbinary.com/blog/rails-7-adds-activerecord-query-methods-in-order-of. 

Want to make a PR?

**Comment by decaffeinatedio** [comment]
@npezza93 Sure, I was struggling with the tests a bit -- they're passing, but I'm not sure if they should be!

https://github.com/npezza93/redi_search/pull/30

I also cleaned up some Rubocop warnings that should be in-line with the cops you've defined.
